# Generated by Django 6.0.5 on 2026-06-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='college_id',
        ),
    ]
