# Generated by Django 6.0.5 on 2026-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0003_food_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
