# Generated by Django 6.0.5 on 2026-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Momos', 'Momos'), ('Drinks', 'Drinks')], default='Pizza', max_length=50),
        ),
    ]
