# Generated by Django 6.0.5 on 2026-06-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
